[Ad-Urls]
#Hagezi = https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/light-onlydomains.txt
#Adguard = https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
#Oisd = https://small.oisd.nl/domainswild2

anti-AD = https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt
AdBlock DNS Filters = https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdomain.txt
